### ISSUE TITLE
App architecture

### ISSUE THREAD

**Issue by mhmdanas** [CentaurusApps/polaris#5]
We still have no concrete plans for the app's architecture. We should create one soon. I'll put my general thoughts here:

- For dependency injection, I find [Riverpod](https://pub.dev/packages/riverpod) to be pretty good.
- We can take inspiration from https://resocoder.com/flutter-clean-architecture-tdd, or maybe even use it as-is. I don't have time to write all my thoughts about it right now though.
- For state management, there are several options, like BLoC or MobX. I'd prefer to keep it simple and use [`state_notifier`](https://pub.dev/packages/state_notifier), which is also supported natively by Riverpod.

Hopefully more discussion will let us flesh out the architecture more.

**Comment by mhmdanas** [comment]
After some discussion, we have a concrete plan now. We will be using Reso Coder's TDD architecture but with one difference: we will be making each layer global instead of being local to each feature (in other words, we won't be using "features" as Reso Coder defines them), and each layer will also be its own package. In other words, we will be making this into a monorepo. Here's how the file structure will look like:
```
polaris/
  - packages/
    - polaris_domain/
      - lib/
        - entities/
        - repos/
        - use_cases/
      - test/
      - pubspec.yaml
      - ...
    - polaris_data/
      - lib/
        - models/
        - data_sources/
        - repos/
      - test/
      - pubspec.yaml
      - ...
    - polaris_presentation/
      - lib/
        - pages/
        - widgets/
        - state_notifiers/ # maybe we should find a shorter name
      - test/
      - pubspec.yaml
      - ...
    - polaris_utils/ # not totally sure if we should have this
      - lib/
      - test/
      - pubspec.yaml
      - ...
  - README.md
  - ...
```

**Comment by PrestoSole** [comment]
I would suggest wrapping the whole structure inside a `features` folder.
